### ISSUE TITLE
iobroker-javascript.connect not found

### ISSUE THREAD

**Issue by menkej** [nokxs/iobroker-javascript-vs-code-extension#103]
**Describe the bug**
After first in stall in VSCode on Windows (and also on a ssh remote linux host) I can't start the connection to the iobroker host

**To Reproduce**
1. CTRL-Shift-P
2. iobroker:Connect to iobroker
3. See error

**Expected behavior**
I expected to go through the config wizard to configure the settings. In my case the config file did not exist yet. The add-on should handle that case. At least the "initial setup" should be described more clearly in README. The current error message is missleading.

**Screenshots**
![image](https://user-images.githubusercontent.com/12273047/198641505-ec8e3ab6-5706-47ed-83c4-900a562cc421.png)

**Version information (please complete the following information):**
 - Extension version: 1.1.4
 - VS Code version: 1.72.2
 - ioBroker admin version: don't even get there
 - ioBroker nodejs version: don't even get there
 - ioBroker javascript adapter version: don't even get there

**Comment by menkej** [comment]
Same error on MacOS.

**Comment by menkej** [comment]
Ok, nach manuellem Anlegen der Konfigurationsdatei, scheint es zu gehen... Ich prüfe...

**Comment by menkej** [comment]
Ok, I think I found my "error". I startet "ioBroker: Connect to iobroker" right away, and did not click on the ioBroker icon first. So I did not see the blue button to help me configure in a wizard style. I'll update the bug description.

![image](https://user-images.githubusercontent.com/12273047/198851521-53237877-31b8-4464-83f3-8ca47403a92d.png)

**Comment by nokxs** [comment]
Danke fürs melden des Problems. In der Version 1.1.5 ist das Problem behoben. Beim Aufrufen des Connect-Kommandos wird die Extension jetzt auch aktiviert und der "Wizard" erscheint um die `.iobroker-config.json` interkativ zu erstellen.
