### ISSUE TITLE
autoupload and run after saving

### ISSUE THREAD

**Issue by Scrounger** [nokxs/iobroker-javascript-vs-code-extension#107]
**Describe the solution you'd like**
Nachdem speichern eines Skriptes z.B. per Tastenkombi Strg+s wäre es super wenn das Skript direkt hochgeladen wird und auch direkt ausgeführt wird. Das würde die Bearbeitung von Skripten bei mir sehr beschleunigen, weil man sich den Mausklick "upload" sparen kann.

Diese Funktion sollte als Option ausgeführt sein, damit der user das selber aktivieren bzw. deaktivieren kann.
Z.B. über die `.iobroker-config.json`, dann wäre das auch möglich gezielt für verschiedene Projekte zu aktivieren bzw. deaktivieren.

Wäre super wenn du das implementieren könntest :-)

**Comment by nokxs** [comment]
Das Feature wird im Release 1.2.0 enthalten sein. Dazu müssen zwei neue Config-Einträge hinzugefügt werden Aus der Doku:

| Key           | Description           | Mandatory | Default |
|---------------|-----------------------|-----------|---------|
| `autoUpload` | Automatically upload scripts on save? | No | false |
| `scriptAutoRun` | Automatically start a uploaded script? | No | false |

**Comment by Scrounger** [comment]
Works great thank you!
