### ISSUE TITLE
Storing PW for diffrent hosts

### ISSUE THREAD

**Issue by Scrounger** [nokxs/iobroker-javascript-vs-code-extension#113]
**Is your feature request related to a problem? Please describe.**
Currently, only one password is stored in the VS Code vault. That means every time you use another host you have to enter the password again.

**Describe the solution you'd like**
The password should be stored per host.

Can you put that in please?

**Comment by nokxs** [comment]
Currently the password and the retrieved token are stored with constant keys in the VS Code secret storage. Would it be a solution to store the secret data with the url and port if ioBroker.

Currently the keys look like this:

```
password
accessToken
```

with the new approach the could look like this

```
password_http://localhost:8081
accessToken_http://localhost:8081
```

With this approach every host would have its own secrets. Would this solve your problem?

**Comment by Scrounger** [comment]
I had already thought of exactly the same solution. Yes, I think that's how it will work.

**Comment by Scrounger** [comment]
Thank you! Works as expected
