### ISSUE TITLE
multiple start of script

### ISSUE THREAD

**Issue by Scrounger** [nokxs/iobroker-javascript-vs-code-extension#116]
**Describe the bug**
I noticed that after my computer was in standby that the scripts are executed multiple times.
The same behavior can be generated when pressing the 'iobroker connected' button.
![grafik](https://user-images.githubusercontent.com/6370451/216043504-630814f7-0a31-4d46-8489-03b3195ce572.png)

**To Reproduce**
1. Start VS Code, save a script and upload it -> script restarts
2. Press the 'iobroker connected' button -> script starts twice
3. Press the 'iobroker connected' button -> script starts three times

**Expected behavior**
Script should only start once.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/6370451/216044280-96c6d16b-0a94-4e3c-930a-350957b4681a.png)

**Version information (please complete the following information):**
 - Extension version: 1.2.1
 - VS Code version: 1.74.3
 - ioBroker admin version: 6.3.5
 - ioBroker nodejs version: 16.x
 - ioBroker javascript adapter version: 6.1.4

**Comment by nokxs** [comment]
I could reproduce this issue and will fix it with the next version.
