### ISSUE TITLE
NewFile with same name instantly deletes the original file

### ISSUE THREAD

**Issue by pino1988** [nokxs/iobroker-javascript-vs-code-extension#117]
**Describe the bug**

**To Reproduce**

- Create new file with same name of the oder files

**Expected behavior**

- Should give a warn and not override the file instantly

**Screenshots**

**Version information (please complete the following information):**
 - Extension version: v1.2.1
 - VS Code version: 1.75.0
 - ioBroker admin version: [e.g. 3.2.16]
 - ioBroker nodejs version: v16.17.1
 - ioBroker javascript adapter version: 6.1.4

**Comment by nokxs** [comment]
I can confirm this bug. It wil be fixed in the next version.

**Comment by nokxs** [comment]
Solved by #120 

Next release will contain this fix.
