### ISSUE TITLE
Icons to upload, download, etc disappeared

### ISSUE THREAD

**Issue by petemadsen** [nokxs/iobroker-javascript-vs-code-extension#119]
The icons (next to the script name) disappeared. It was working a week ago exactly as it is show in the README video.

I can still upload and download the scripts using the Ctrl+Shift+P method using the "iobroker" commands.

**Screenshots**
![tmp-2023-03-01-next-file-1](https://user-images.githubusercontent.com/1626463/222053751-e68eea08-5483-4a73-bb70-4351399a53a6.png)

**Version information (please complete the following information):**

 - Extension version: 1.2.1
 - VS Code version: 1.75.1
 - ioBroker admin version: admin6
 - ioBroker nodejs version: 18.13.0
 - ioBroker javascript adapter version: 6.1.4

**Comment by nokxs** [comment]
It looks like you are in the view "Explorer" and not in the view "iobroker". The buttons are only visible in iobroker-view:

![grafik](https://user-images.githubusercontent.com/5887690/223827778-adec4697-0385-4418-9547-2226a3d957ef.png)

Can you confirm the buttons are missing in the iobroker-view?

**Comment by nokxs** [comment]
Closed stale issue.
