### ISSUE TITLE
Could not connect to ioBroker

### ISSUE THREAD

**Issue by Spampunk** [nokxs/iobroker-javascript-vs-code-extension#123]
Ich bekomme keine Verbindung zu meinem ioBroker hin. Der Server läuft auf Debian, ich möchte remote drauf zugreifen. ioBroker ist bei mir passwortgeschützt, ohne SSL (also HTTP).

![image](https://github.com/nokxs/iobroker-javascript-vs-code-extension/assets/47517540/28449d0f-515c-4d82-a002-864059c47a53)

![image](https://github.com/nokxs/iobroker-javascript-vs-code-extension/assets/47517540/407a8d26-ab91-4502-a300-46d919ea0d10)

Danke und viele Grüße!

**Version information (please complete the following information):**
 - Extension version: v1.2.2
 - VS Code version: 1.78.2
 - ioBroker admin version: 6.3.5
 - ioBroker nodejs version: v18.16.0
 - ioBroker javascript adapter version: 4.0.24

**Comment by Feuer-sturm** [comment]
@Spampunk Die Zeile username fehlt bei dir. Schau mal nach den Parametern in der Readme auf der Startseite hier vom Repository. 
Hier findest du eine Beispiele config https://github.com/nokxs/iobroker-javascript-vs-code-extension/blob/main/doc/.iobroker-config.json

**Comment by nokxs** [comment]
Closed stale issue.
