### ISSUE TITLE
Darstellung der laufenden Skripte ist falsch herum angezeigt

### ISSUE THREAD

**Issue by mcuiobroker** [nokxs/iobroker-javascript-vs-code-extension#124]
Die laufenden Skripte werden in der Extension als nicht laufende Skripte dargestellt.

**Screenshots**
![image](https://github.com/nokxs/iobroker-javascript-vs-code-extension/assets/84818934/a29f952d-66f2-4c1f-b2fc-21f40be95744)
in ioBroker
![image](https://github.com/nokxs/iobroker-javascript-vs-code-extension/assets/84818934/369057b6-0f35-41b6-885b-c15b3cafade4)

**Version information (please complete the following information):**
 - Extension version: 1.3.0
![image](https://github.com/nokxs/iobroker-javascript-vs-code-extension/assets/84818934/6c9014e5-dc70-473d-8ef9-9499ec3d1ed7)

 - VS Code version: 1.81.1
![image](https://github.com/nokxs/iobroker-javascript-vs-code-extension/assets/84818934/566e09e2-8ce5-4ddc-a712-1a0f9b968a53)

 - ioBroker admin version: 6.9.1
 - ioBroker nodejs version: 18.17.1
 - ioBroker javascript adapter version:0 7.1.1

**Comment by nokxs** [comment]
Ausgehend von den Screenshots passt alles, da die Skripte auch in ioBroker selbst nicht als laufend angezeigt werden. Skripte mit einem roten Dreieck als Symbol laufen nicht und welche mit dem grünen Playzeichen laufen.

**Comment by mcuiobroker** [comment]
Ich meinte die Logik, bei den laufenden Scripts steht das Pausenzeichen
![image](https://github.com/nokxs/iobroker-javascript-vs-code-extension/assets/84818934/b95f0f36-3747-410f-8c2e-20b24cd13113)
In VSCode steht dort dann ein Dreieck.
![image](https://github.com/nokxs/iobroker-javascript-vs-code-extension/assets/84818934/9bf065a1-2315-494e-a482-d1e3503ceb89)
Aber wenn das so sein soll. ok.

**Comment by nokxs** [comment]
Ja das war eine bewusste Entscheidung. In ioBroker sind die Icons gleichzeitig auch Buttons und geben dadurch an, welche Aktion durch den Click ausgelöst wird. In VS Code hab ich an der Stelle leider keinen  Button zur Verfügung und kann nur ein Icon anzeigen. Das Icon zeigt dann den aktuellen Zustand.

**Comment by chris299** [comment]
@nokxs vielen Dank für Deine tolle Arbeit. 
Für die UX wäre es evtl. hilfreich an dieser Stelle andere Icons als die im Iobroker zu nehmen, wenn es hier andere Bedeutungen hat., z.B. ein Viereck für gestoppte Skripte.
(ich habe eh nie verstanden, warum "Pause", wenn ein Skript nicht läuft, weil es doch immer von vorn startet, wenn man es nach "Pause" wieder startet....)

▶️ Läuft
⏹️ Gestoppt

**Comment by nokxs** [comment]
@chris299 Die Idee finde ich gut. Kannst du einen neuen Issue dafür anlegen? Ich schaue es mir dann bei Gelegenheit an.
