### ISSUE TITLE
Die Hauptordner (Common und Global) werden nicht erkannt

### ISSUE THREAD

**Issue by tt-tom17** [nokxs/iobroker-javascript-vs-code-extension#126]
**Describe the bug**
Die Hauptordner (Common und Global) werden mit der JavaScript - Adapter Version 7.5.0 nicht mehr richtig erkannt. Dadurch funktioniert die Zuordnung der Dateien(Scripts) nicht mehr. 

**Screenshots**

<img width="960" alt="image" src="https://github.com/nokxs/iobroker-javascript-vs-code-extension/assets/101348966/0b8b18e5-4d31-46b8-b861-03be7eccc6e7">

**Version information (please complete the following information):**
 - Extension version: 1.3.0
 - VS Code version: 1.85
 - ioBroker admin version: 6.12.9
 - ioBroker nodejs version: 18.19.0
 - ioBroker javascript adapter version: 7.5.0

**Comment by jadirc** [comment]
Ich habe das selbe Problem seit dem Update.

**Comment by nokxs** [comment]
Ich schau mir das die Tage Mal an.

**Comment by tt-tom17** [comment]
habe das Problem gefunden. In den Objektdaten wurde der Name auf weitere Sprachen erweitert, dadurch ergibt sich eine andere Lesart.

alte Variante
```
{
  "_id": "script.js.common",
  "type": "channel",
  "common": {
    "name": "common"
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1703268866787
}
```

neue Variante
```
{
  "_id": "script.js.common",
  "type": "channel",
  "common": {
    "name": {
      "en": "Common scripts (common)",
      "de": "Allgemeine Skripte (common)",
      "ru": "Общие скрипты (common)",
      "pt": "Scripts comuns (common)",
      "nl": "Common scripts (common)",
      "fr": "Scénarios communs (common)",
      "it": "Scrittori comuni (common)",
      "es": "Scripts comunes (common)",
      "pl": "Common script (common)",
      "uk": "Загальні сценарії (common)",
      "zh-cn": "共同说明 (common)"
    }
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1703268866787
}
```
aktuelle Lösung erstmal ist das Zurücksetzen auf die alte Variante im iobroker.

**Comment by nokxs** [comment]
Das war ein sehr guter Hinweis und hat mir die Fehlersuche vereinfacht :-). In Version 1.3.1 sollte das Problem behoben sein.

**Comment by tt-tom17** [comment]
leider negativ. Habe die Ordner auf die aktuelle Beschreibung umgestellt und neu geladen, dass selbe Resultat.
<img width="358" alt="Bildschirmfoto 2023-12-23 um 17 50 40" src="https://github.com/nokxs/iobroker-javascript-vs-code-extension/assets/101348966/c409173d-0731-404d-815a-6ef5b268e800">
<img width="358" alt="Bildschirmfoto 2023-12-23 um 17 51 23" src="https://github.com/nokxs/iobroker-javascript-vs-code-extension/assets/101348966/28684d03-8f9d-4319-932b-6acdb25a4a17">

Das Problem sehe ich aktuell beim erstellen der Verzeichnisse auf dem PC, wo VS läuft.
Die zweite Hürde wird sein, dass die JavaScript Version noch Beta ist, aber irgendwann kommt.

**Comment by nokxs** [comment]
Sieht besser aus wie vorher, aber noch nicht gut 😁. Ich schaue mir das nochmal an und versuch das bei mir zu reproduzieren.

**Comment by tt-tom17** [comment]
du brauchst nur den Abschnitt "name": {...} übernehmen in die Objektdaten, dann siehst du die Änderungen. Du bekommst ein Objekt dadurch zurück.

**Comment by nokxs** [comment]
Nächster Versuch. Hast du das Problem noch mit Version 1.3.2?
