### ISSUE TITLE
Support Admin 7

### ISSUE THREAD

**Issue by anwa** [nokxs/iobroker-javascript-vs-code-extension#132]
Admin 7.0.1 and js-controller 6.0.2 are on the way.
Can you please update the extension to support this version?
I did not test if admin6 setting works with admin 7 but it would be better to have admin7 setting anyways.

**Comment by nokxs** [comment]
I just tested the extension with Admin 7.0.1, js-controller 6.0.5 and javascript 8.6.0 and can confirm it is still working as expected with admin 6 setting. Nonetheless I will add a admin 7 setting in the config to avoid confusion.
