### ISSUE TITLE
Could you please improve the "Hover over state id string" information?

### ISSUE THREAD

**Issue by neopholus** [nokxs/iobroker-javascript-vs-code-extension#141]
Is your feature request related to a problem? Please describe.
I added this wish already to #137, but this is already closed and this is not related to the improvement requested in #137, thus I think, opening a new issue is better.

The current info box shown when hovering over any string with a full state id to show current data of the state is great, if the IDs of states have good, memorable names like `0_userdata.0.ccu2.updateAvailable`.
But for working with Homematic IP, there is a problem, as the IDs all look like this:

    hm-rpc.1.0000D3D996043E
    hm-rpc.1.0000C3C8960358
    ....

I have dozens of those devices and the hover info box looks like:
![grafik](https://github.com/user-attachments/assets/cc198bf6-e56c-45ae-9ded-071255f7be39)

Describe the solution you'd like
Showing the name corresponding to an id in the hover info box would be a big help for me, e.g. like
![grafik](https://github.com/user-attachments/assets/800dc4f6-dff0-4e98-a683-817b11f26102)

Additional information, e.g. like the one shown during Intellisense autocompletion, would be great, too:
```
Role: indicator
Type: boolean
Readable: true
Writable: true
```
Maybe consolidate both info boxes?

Describe alternatives you've considered
--none--

@nokxs: Do you have an Amazon wish list or some other way to accept donations for this awesome extension? It made script development for iobroker SO MUCH MORE COMFORTABLE for me and I would like to support further development. I know that must be a lot of work.

**Comment by nokxs** [comment]
I like your Idea and just implemented the feature. It is added with version 1.5.0.

Support of my work is highly appreciated. If you like, you can use https://buymeacoffee.com/nokxs for support. Thanks in advance.

**Comment by neopholus** [comment]
Thanks a lot 🥇! Unfortunately, I currently do not have access to my ioBroker installation, but the ☕☕☕ are sent.
Hopefully, the fees do not eat up too much of them. I will test next week. The support for this extension is really great!

**Comment by nokxs** [comment]
Thanks you for the many coffees.  It really motivates, getting some support :-)

**Comment by neopholus** [comment]
Works great! Thanks!
