### ISSUE TITLE
Could you please add a comment containing the name of the iobroker state behind the Auto completion (IntelliSense) of ioBroker state ids?

### ISSUE THREAD

**Issue by neopholus** [nokxs/iobroker-javascript-vs-code-extension#146]
**Is your feature request related to a problem? Please describe.**
If I use Intellisense to add an ioBroker state id, it looks like:
`setState('hm-rpc.1.00089B4092E667.2.STATE', true, false); `

For Homematic adapter and many others, these IDs are not very "user-friendly" and the devices cannot be easily identified by looking at the id. 

**Describe the solution you'd like**
Do not only auto complete the ID, but also the name as a comment behind the ID (this is done by the internal ioBroker Javascript editor). It looks like e.g.: 
`setState('hm-rpc.1.00089B4092E667.2.STATE' /* WZ.Mainlight:Actor 1.STATE */, true, false); `

**Describe alternatives you've considered**
Currently, the info box shown when hovering over the ID shows also the name. This is already a very helpful improvement.

**Additional context**
I documented some ideas on how to do that already [here](https://github.com/nokxs/iobroker-javascript-vs-code-extension/issues/137#issuecomment-2290749294), but as the issue was already closed, I assume, this was overlooked. And maybe it is not useful at all.

**Comment by nokxs** [comment]
I thought about this and i don't want to add the comment every time a ID is auto completed. Instead I thought about adding a Code Action on an ioBroker ID. Code Actions are the little light bulb, which appear some times. [More info here}(https://code.visualstudio.com/docs/editor/refactoring).

So you would press the light bulb (or the corresponding key binding) and would get the option add the name as comment to the id.

Would this be viable solution for you?

**Comment by neopholus** [comment]
After thinking about it: yes, sounds lika a viable solution. Did not think about that before.

Add on: I "simulated" the required steps for my use case with your proposed solution and I think, it will work great, as I also do not need the comment for all IDs. Effort to add a comment in case I need it is completely acceptable.

**Comment by nokxs** [comment]
Solved with #150.

See [documentation](https://github.com/nokxs/iobroker-javascript-vs-code-extension?tab=readme-ov-file#add-name-of-iobroker-objectstate-id-as-comment) on how to use it.

**Comment by neopholus** [comment]
Awesome! Thanks a lot!
