### ISSUE TITLE
IntelliSense/Autocompletion is sometimes wrong

### ISSUE THREAD

**Issue by neopholus** [nokxs/iobroker-javascript-vs-code-extension#147]
**Describe the bug**
In some situations, the autocompleted value is not replacing the already existing text correctly.
I assume, the hyphen in the name is the problem. And only, if the hyphen is already typed before the IntellySense kicks in.

**To Reproduce**
1. Enter `setState('hm-rp'`
2. With the cursor after the 'p' press CTRL+Space to activate IntelliSense
3. select `hm-rpc` and press '.' or tab
4. See error: `setState('hm-hm-rpc'`

Same for `vis-hqwidgets` or `simple-api` (start IntelliSense AFTER the hyphen was typed!).

**Expected behavior**
Expected behavior is `setState('hm-rpc'`

**Screenshots**
![grafik](https://github.com/user-attachments/assets/854fd0e0-6f07-4c02-babd-c1407979ff8b)

**Version information (please complete the following information):**
 - Extension version: v1.5.0
 - VS Code version: 1.92.1
 - ioBroker admin version: 7.0.22
 - ioBroker nodejs version: v18.20.4
 - ioBroker javascript adapter version: 8.7.6

**Comment by nokxs** [comment]
I was able to reproduce the behaviour and I will try to fix it soon.
