### ISSUE TITLE
Kann man ein ioBroker Skript in VSCode debuggen

### ISSUE THREAD

**Issue by neopholus** [nokxs/iobroker-javascript-vs-code-extension#152]
Kurze Frage: Kann man ein Skript, das man zum ioBroker hochgeladen hat und dort läuft in VSCode mit dieser Extension debuggen? Und wenn ja, wie? Lokal in ioBroker geht das (so einigermaßen), aber ich habe keine Ahnung, ob und wie das in VSCode geht.

**Comment by nokxs** [comment]
Nein, das geht stand jetzt nicht und ich weiß auch nicht wie ich das umsetzen könnte. Das Feature wird bis auf weiteres nicht kommen, weswegen ich den Issue hier gleich wieder schließen werde.
