### ISSUE TITLE
Verbindung zum iobroker

### ISSUE THREAD

**Issue by Klaus-Lucas** [nokxs/iobroker-javascript-vs-code-extension#153]
Ich habe VSC auf Windows installiert und iobroker läuft auf einer VM unter Proxmox.
In der readme ist es dann nicht klar, welchen User in "username" einzutragen ist.
Ist es der User, den ich zum Anmelden an die iobroker GUI nehme oder der Linux User der VM?
Habe beides getestet und bekomme bei beiden Varianten diese Fehlermeldung:

![klu_031](https://github.com/user-attachments/assets/a16fdbbc-9f5d-46e0-8bf9-077864d74243)

![klu_029](https://github.com/user-attachments/assets/1b0bae8d-9499-4ee3-9edc-3b844fec85a5)

Admin Version 7.2.6
![klu_036](https://github.com/user-attachments/assets/cd54216f-e9ac-4c79-862e-e43775936803)

**Comment by nokxs** [comment]
Hallo, da die Extension nichts über Proxmox weiß, muss als Benutzername der ioBroker Benutzerame eingetragen werden, also der welcher in der ioBroker GUI verwendet wird. Ich versuch das in der Readme noch etwas genauer zu beschreiben. 

Ist die ioBroker GUI von dem Rechner aus, auf welchem VS Code installiert ist unter `http://192.168.178.41:8081` erreichbar?

Falls es weiterhin nicht klappt, bitte das Debug Log einschalten (siehe `collectDebugLog` in https://github.com/nokxs/iobroker-javascript-vs-code-extension?tab=readme-ov-file#available-settings) und hier anhängen. Ich schaue dann bei Gelegenheit drauf, ob ich das Problem entdecken kann.

**Comment by Klaus-Lucas** [comment]
Hallo Niklas,
ja, iobroker und der Windows PC mit VSC sind 2 verschiedenen Rechner.
Die iobroker GUI ist vom Windows PC problemlos aufzurufen.
![image](https://github.com/user-attachments/assets/5fbf62a0-d081-42a2-aa52-d56195588048)

Das Problem war das Passwort, was ein "&" enthalten hat. Nach Austausch gegen ein anderes Zeichen, ging es dann:
![image](https://github.com/user-attachments/assets/a7a35cd2-5bc9-458c-b833-8b4f8848cf80)

**Comment by nokxs** [comment]
Sehr schön, dass es geklappt hat. 

Ich hab gerade bei mir auch probiert ein Passwort mit einem "&" zu verwenden und es hat bei mir auch nicht funktioniert. Bei Gelegenheit werde ich das Problem debuggen und schauen, ob es sich lösen lässt.

**Comment by Klaus-Lucas** [comment]
ich kann zwar ein Script jetzt editieren, aber beim abspeichern landen die Änderungen nicht im iobroker. Es gibt ein youtube Video für das Thema von Matthias, aber da wird nicht gezeigt, wie man im VSC die Einstellungen machen muss. Dto. für Github. Hast du im Internet da was ausführlicheres gefunden?

**Comment by nokxs** [comment]
Du musst die Skripte hochladen, ein einfaches speichern reicht nicht. Beim speichern sind diese erst einmal nur lokal auf der Festplatte gespeichert. Siehe hier in der Doku: https://github.com/nokxs/iobroker-javascript-vs-code-extension?tab=readme-ov-file#upload-scripts

**Comment by Klaus-Lucas** [comment]
Lies bitte mal das PDF
[Visual Studio Code installieren.pdf](https://github.com/user-attachments/files/17773467/Visual.Studio.Code.installieren.pdf)

**Comment by nokxs** [comment]
Ich hab mir deine PDF angeschaut und dein Problem verstanden: Du hast initial die Skripte nicht heruntergeladen, womit die nie auf deiner Festplatte gelandet sind. Aus dem Grund steht im Script Explorer neben den Scripts auch "only Remote", was bedetued, dass diese nur in der ioBroker Instanz existieren. Um die Skripte ändern zu können, müssen diese auf der lokalen Festplatte vorhanden sein. Am einfachsten ist es alle Skripte auf einmal herunterzuladen:

![grafik](https://github.com/user-attachments/assets/e5daf9f6-b50e-4a08-8e29-6658f30fc64b)

Anschließend kannst du das Skript editieren und hochladen. Sobald du es editiert und gespeichert hast, sollte es auch bei "Changed Scripts" auftauchen. 

Script root ist übrigens ein relativer Pfad innerhalb deines VS Code Workspaces und hat nichts mit dem Verzeichnis auf deinem Server zu tun. Das ist rein lokal auf deinem Windows Rechner.

Ich werde die Readme anpassen um das etwas klarer zu machen und ich werden versuchen das initiale Verbinden etwas intuitiver zu gestalten.

**Comment by Klaus-Lucas** [comment]
Noch eine Kleinigkeit. Bei der Workspace-Abfrage bietest du einen Slash als Default-Wert an. 
Da Windows, müsste es nicht ein Backslash sein?

**Comment by nokxs** [comment]
Nein, muss nicht zwinged ein back Slash sein, da Windows heutzutage auch mit forward Slash umgehen kann. 

Da ich hoffentlich deine Probleme behoben habe, werde ich den Issue hiermit schließen.
