### ISSUE TITLE
Support password protected ioBroker installations

### ISSUE THREAD

**Issue by nokxs** [nokxs/iobroker-javascript-vs-code-extension#26]
Currently it is not possible to connect to a password protected ioBroker installation.

This should be supported.

**Comment by Sputnik24** [comment]
Any news here?

**Comment by nokxs** [comment]
Sorry, I haven't done any work on it yet. I will try to have a look into it the next few weeks.

**Comment by nokxs** [comment]
Small update: I found a way to support password protected ioBroker installations, but still need some time to implement it.

**Comment by Feuer-sturm** [comment]
Thanks for this feature. I just made a test and the connection could be enabled :-)
I just need to add for my username the line in the config:
`  "username":"admin"`
