### ISSUE TITLE
Lässt Admin Instanz abstürzen

### ISSUE THREAD

**Issue by ciddi89** [nokxs/iobroker-javascript-vs-code-extension#30]
**Describe the bug**
Wenn VSCode geöffnet ist und man noch verbunden ist mit ioBroker und man dann ioBroker neu startet (hier Container neu starten), beginnt bei ioBroker der RAM voll zu laufen bis 4-7GB und man kommt nicht bzw. sehr schwer auf ioBroker. Hab paar Tage gebraucht das zu finden da ich nicht wusste das noch ein Fenster mit VSCode und den ioBroker Plugin auf mein Rechner offen war. Sobald man das geschlossen hat und ioBroker danach noch mal neu startet ist der Fehler weg und alles läuft wieder.

**To Reproduce**
1. Let VSCode with the ioBroker plugin open
2. Restart ioBroker
3. Wait and try to open the admin page of ioBroker in your browser 
4. Ram consumption soars
5. Admin instance crashes

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Browser: Safari, Chrome
 - Version: newest

**Additional context**
ioBroker runs with Docker on Synology DS716+. ioBroker runs with Node.js 12.20.2 and js-Controller 3.2.16

**Comment by nokxs** [comment]
Ich habe gerade versucht den Fehler bei mir zu reproduzieren, schaffe es aber nicht. 

Versucht habe ich es mit dem js-controller 3.1.8 und 3.2.16 auf zwei x86 Rechner und bei beiden läuft ioBroker im Container. Der eine Rechner läuft mit Windows der andere mit Ubuntu.

Ich könnte mir vorstellen, dass es mit einem der installierten Adapter zusammenhängt. Tritt bei dir das Problem auch mit einem neuen Container ohne extra installierte Adapter auf?

**Comment by ciddi89** [comment]
Hi, 

Danke erstmal für den Versuch den Fehler zu finden. Das kann gut sein das es mit einem Adapter zu tun hat. Wenn ich nämlich alle Adapter beende und ioBroker neu starte, dann komme ich drauf. Aber sobald ich dann ein paar Instanzen, egal welche, starte dann fängt es an das der RAM sich hoch schaukelt und die Admin Instanz lädt und lädt und lädt. Schade das du das nicht reproduzieren kannst, wüsste gern was da das Problem bei mir erzeugt. Wobei nun weiß ich ja das der Fehler kommt und gucke bei einem Neustart das das Plugin nicht mit ioBroker verbunden. 

LG

**Comment by nokxs** [comment]
Ich habe gerade noch einmal versucht das Problem nachzustellen, indem ich wahllos ein paar Adapter installiert und anschließend den ioBroker Docker Container neu gestartet habe. Nach wie vor habe ich es nicht geschafft, das Problem zu reproduzieren. 

Könntest du mir sagen, mit welcher Kombination von Adapter der Fehler bei dir auftritt?

**Comment by ciddi89** [comment]
Hmm okay. Ich werde die Tage zuhause noch einmal probieren ob der Fehler auftaucht. Und wenn ja werde ich mal eine Bildschirmaufnahme mit laufen lassen. Ich denke das ist unabhängig von einem Adapter. Weil am Anfang wenn man ohne irgendwelche Adapter startet, verhält sich der RAM auch schon merkwürdig. Fällt aber nicht so auf weil keine Adapter gestartet sind und der RAM dann nur bei 200-400 Mb ist.. und egal in welcher Reihenfolge man diese dann startet bzw. Egal welchen Adapter man startet, er kackt ab. Naja werde noch mal gucken und wenn dann ein link der Aufnahme hier posten + eine Liste der Adapter.  Vielleicht hilft dir das dann weiter. Oder es liegt irgendwie an mein System. 🤷🏼‍♂️

**Comment by patrickbs96** [comment]
Ich hatte gerade das gleiche Problem. ioBroker hat sich aufgrund eines Fehlers neugestartet und war dann nicht mehr erreichbar. Der iobroker.js-controller hat daraufhin den Speicher vollgemacht und mein Pi war kaum noch bedienbar. Konnte mich dann an dieses Issue erinnern und nachdem ich VSCode geschlossen hatte konnte ich wieder damit arbeiten 🤔

**Comment by nokxs** [comment]
Ich schau mir das die nächsten Tage nochmal an, ob ich da was in die Richtung rausfinde und den Fehler reproduzieren kann.

**Comment by Feuer-sturm** [comment]
@nokxs @ciddi89 Ich kann bei mir das gleiche Verhalten beobachten. Mein ioBroker mit js-controller 3.2.16 läuft in einem LXC Container (Ubuntu 18.04.5). Ich hatte in letzter Zeit häufiger das Problem, dass ich mein ioBroker nicht gestartet ist und mir der RAM auch voll gelaufen ist.

Hatte gerade wieder das Problem und nebenbei auch VSCode mit der ioBroker anbindung offen.

Bei mir im ioBroker log tauchen dann u.a. solche Warnings und Errors auf:
![grafik](https://user-images.githubusercontent.com/25422320/114319024-f0b2da80-9b0f-11eb-816a-0611f97d0eea.png)


Im Syslog vom Promox PVE steht dann irgendwann folgendes, wenn der RAM voll gelaufen ist:
Apr 11 21:07:57 pve kernel: [1915142.696839] node invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0


Und im Syslog vom ioBroker Container kommt daraufhin: 
Apr 11 21:07:58 ioBrokerBETA systemd[1]: iobroker.service: Main process exited, code=killed, status=9/KILL
Apr 11 21:08:20 ioBrokerBETA systemd[1]: iobroker.service: Failed with result 'signal'.
Apr 11 21:08:20 ioBrokerBETA systemd[1]: iobroker.service: Service hold-off time over, scheduling restart.


Ich hab gerade VSCode geschlossen und ioBroker ist sauber gestartet.


Helfen dir irgendwelche ioBroker Logs oder sysLogs vom PVE / Container?

**Comment by nokxs** [comment]
@Feuer-sturm Danke für die ausführliche Meldung. Da ich immer noch keine Ahnung habe, was das Problem ist wäre es gut, wenn du mir alle logs zur Verfügung stellen kannst die du hast. Eventuell kann ich da was rauslesen.

**Comment by Feuer-sturm** [comment]
@nokxs Kann ich dir die Logs irgendwie direkt zukommen lassen?

**Comment by Feuer-sturm** [comment]
Logs hat @nokxs . Hoffentlich findet er was in den Daten :-)

**Comment by nokxs** [comment]
Ich hab mir inzwischen intensiv die Logs angeschaut, bin aber nicht so richtig schlau daraus geworden. Ich habe im PR #43 eingeführt, dass bei einem Reconnect die Verbindung erst einmal getrennt wird und im Abstand von 2 Sekunden wird anschließend versucht eine neue Verbindung aufzubauen. 

Da ich den Fehler bei mir immer noch nicht nachstellen konnte, kann ich nicht garantieren, dass das hilft. Hier bin ich auf die Rückmeldung von euch angewiesen.

Getest werden kann das Verhalten mit der gerade eben veröffentlichten Version 0.10.0 in Verbindung mit Admin 4.

Was in der Version auch neu ist, ist die Admin 5 Untersützung. Da hier der Verbindungsaufbau komplett anders funktioniert, hoffe ich, dass der Fehler dort nicht auftritt.

**Comment by Feuer-sturm** [comment]
@nokxs Dann werde ich mal schauen, ob ich mit der 0.11 und Admin4 und Admin5 das System noch zum Absturz bekomme.

**Comment by Feuer-sturm** [comment]
@nokxs Es sieht nicht gut aus. iobroker.javascript 0.11.0 und Admin 4.2.1 (Ich weiß nicht ob es eine Rolle spielt. Mein ioBroker läuft in einem unpreviligiertem LXC Container unter Proxmox)

Es taucht das gleiche Fehlerbild auf. Der RAM läuft voll und ioBroker startet neu.

Ablauf:
VSCode mit bestehenden Verbindung zum ioBroker offen lassen und dann ein iobroker stop und iobroker start

![grafik](https://user-images.githubusercontent.com/25422320/115921265-8d179e00-a47b-11eb-89d9-dbea43625ebc.png)

**Comment by patrickbs96** [comment]
Ich muss leider das gleiche bestätigen wie @Feuer-sturm mit Admin 5.0.7. Bin genauso vorgegangen und erst nachdem ich VSCode geschlossen hatte beruhigte sich der raspberry Pi wieder. Die Auslastung der CPU betrug beinah 100%.

**Comment by nokxs** [comment]
Schade, dass es nicht geklappt hat.

Würde es euch erst einmal helfen das reconnect Verhalten konfigurierbar zu machen? Damit könntet ihr den reconnect abschalten und ihr müsstet euch manuell wieder verbinden, sobald ihr es braucht.

**Comment by patrickbs96** [comment]
Finde ich eine gute Idee, dann gibt es zumindest erstmal keine Probleme damit. 

Mir fällt gerade noch ein, die Extension hat direkt nach dem Start von ioBroker den Status auf connected geändert. Könnte es eventuell etwas damit zu tun haben, dass die Extension sich zu früh im Startprozess verbindet? 
Fühlt sich irgendwie so an als würde der ioBroker in einer Endlosschleife feststecken solange die Connection aufgebaut ist 🤔 
Habe mir deinen Code einmal kurz angeschaut aber ich verstehe den nicht gut genug um das selbst zu testen. Die Sprache gehört noch nicht zu meinem repertoire

**Comment by nokxs** [comment]
Ab der Version 0.11.1 ist der automatische Reconnect konfigurierbar und damit optional (siehe https://github.com/nokxs/iobroker-javascript-vs-code-extension#available-settings --> autoReconnect). Neu ist auch, dass man in der Statusleiste auf den Verbindungsstatus klicken kann, um sich (neu) zu verbinden. 

Ich hoffe, dass euch das weiterhilft.

**Comment by Feuer-sturm** [comment]
@nokxs Danke. Werde es ausprobieren. Hab jetzt den autoReconnect auf false gesetzt und kann schon einmal sagen, dass in der Statusleiste in VSCode ein ioBroker disconnected stetht und beim Klicken auf den Verbindungsstatus die Verbindung hergestellt wird. :-)

**Comment by Feuer-sturm** [comment]
@nokxs auch mit der 0.11.1 hab ich das System wieder zum Absturz gebracht.
Bei 1 hatte ich die 0.11.1 installiert und den ioBroker neu gestartet und ihn bis ca. 23 Uhr Zeit den VScode Adapter auf disconnected gelassen und ihn dann connected. Ich hab auch einfacch ein paar mal mehr zwischendurch auf "connected" gedrückt :-)

Gerade hab ich gesehen, dass der Speicher wieder vollgelaufen ist und ioBroker neu gestartet wurde (bei 2).

![grafik](https://user-images.githubusercontent.com/25422320/115973548-20bd9d00-a556-11eb-8e32-08657a4f4d9f.png)

**Comment by ciddi89** [comment]
Hallo,

ich kam auch endlich dazu es noch einmal zu testen. Fehler besteht weiter hin. Dadurch das du aber die autoreconnect Funktion eingefügt hast und man diese nun auf false stellen kann, brauch ich keine Angst mehr haben das es ioBroker wieder zum Absturz bringt. Die Verbindung disconnected wenn ioBroker neugestartet wird und dieser startet dann vernünftig. Vielen Dank schon mal dafür. Würde mich trotzdem interessieren was da so Probleme macht bei bestehender Verbindung und warum das bei dir nicht vorkommt.🤔

**Comment by nokxs** [comment]
Hi, würde mich auch interessieren woher das kommt. Mal schauen, ob ich die nächsten Tage nochmal dazu komme mir das genauer anzuschauen. 

Habt ihr mit Admin 5 eigentlich das gleiche Problem?

**Comment by ciddi89** [comment]
> Habt ihr mit Admin 5 eigentlich das gleiche Problem?

Hab ich noch nicht getestet da ich nur ein produktiv System habe und Admin 5 noch in Alpha ist. Auch wenn es mir in den Fingern juckt zu updaten. 🤓

**Comment by Feuer-sturm** [comment]
Admin5 hab ich auf meinem Testsystem. Bin aber noch nicht dazu gekommen das Problem damit nachzustellen. Kommt aber in Kürze.

**Comment by patrickbs96** [comment]
Ich bekomme es mit Admin5 bei beiden Konfigurationseinstellungen hin den Fehler auszulösen. 
Vielleicht hat das was mit dem Fall von @Feuer-sturm zu tun.
Mit Admin4 habe ich das jetzt nicht getestet.

Aktivierter Reconnect:
1. ioBroker stoppen
2. VSCode offen
3. ioBroker starten
5. Browser zum Admin öffnen
6. Speicher läuft innerhalb ein paar Minuten voll

Deaktivierter Reconnect:
1. ioBroker stoppen
2. VSCode offen
3. ioBroker starten
4. manueller Reconnect
5. Browser zum Admin öffnen
6. Speicher läuft innerhalb ein paar Minuten voll

In beiden Fällen wird es durch das Öffnen des Admins über den Browser ausgelöst.
Ich habe auch einige Minuten mal gewartet bevor ich den Browser geöffnet habe aber der Speicher läuft trotzdem voll.
Nachdem Browser und VSCode geschlossen sind beruhigt sich das System wieder. Danach kann beides auch wieder ohne Probleme geöffnet werden.

Ich nutze Admin 5.0.9

**Comment by nokxs** [comment]
Ich hatte den Fehler auch einmal mit Admin 5. Mit Admin 6 aber noch nicht. Ist dies bei euch auch so?

**Comment by ciddi89** [comment]
> Ich hatte den Fehler auch einmal mit Admin 5. Mit Admin 6 aber noch nicht. Ist dies bei euch auch so?

Hatte eben Zeit dies zu testen. Scheint mit Admin 6 nicht mehr vorzukommen.

**Comment by nokxs** [comment]
Ich mach den Issue zu, da das Problem mit Admin 6 scheinbar nicht mehr auftaucht.
