### ISSUE TITLE
Script status is not updated correcly in script explorer

### ISSUE THREAD

**Issue by nokxs** [nokxs/iobroker-javascript-vs-code-extension#31]
**Describe the bug**
The status if a script is running/stopped in the script explorer is not updted correctly after a script is stopped or started. If the script is started/stopped again, the status is shown correctly.

**To Reproduce**
1. Go to ScriptExlorer
2. Start/stop a script
3. The status is not displayed correctly
4. Start/stop the scirpt again
5. The status is displayed correctly

**Comment by Feuer-sturm** [comment]
Bugfix is working. Thanks.
