### ISSUE TITLE
Unable to upload empty file

### ISSUE THREAD

**Issue by TomaT3** [nokxs/iobroker-javascript-vs-code-extension#36]
**Describe the bug**
If you clear all text in an existing file and you want to upload the empty file without content, nothing happens.

**To Reproduce**
1. Create a new file at ioBroker scripts (I created a TypeScript file)
2. Download the file with the extension
3. Add some content to the file (just some comment will be enough)
4. Upload the file with the extension
5. You will see the changes in ioBroker scripts, the file was uploaded succesfully
6. Clear the content of the file and uload it with the extension
7. Nothing happens. Content is still in the file when you check ioBroker scripts

**Expected behavior**
File without no content should be uploaded with no content.

**Desktop:**
 - ioBroker.javascript v0.9.1
 - OS: Windows 10 Pro Insider Preview 21318.1000
 - Browser: Chrome Version 89.0.4389.90
 
![image](https://user-images.githubusercontent.com/13355291/111881004-d2453d80-89ae-11eb-89d9-679e786985c9.png)
![image](https://user-images.githubusercontent.com/13355291/111881023-e9842b00-89ae-11eb-97d1-364a1aa56b0b.png)
![image](https://user-images.githubusercontent.com/13355291/111881048-120c2500-89af-11eb-8b9e-b20a14b599d1.png)

**Comment by nokxs** [comment]
This bug is fixed in v0.9.2
