### ISSUE TITLE
Keine Verbindung zum ioBroker möglich mit Admin 5

### ISSUE THREAD

**Issue by patrickbs96** [nokxs/iobroker-javascript-vs-code-extension#38]
**Describe the bug**
Nach Upgrade des Admins auf die Version 5.0.3 war keine Verbindung zum ioBroker mehr möglich. Nach einem Downgrade auf 4.0.10 war eine Verbindung wieder möglich. Vielleicht ist es aber auch ein Fehler im Admin.

**To Reproduce**
1. Upgrade Admin nach 5.0.3
2. VS Code öffnen

**Expected behavior**
Verbindung zum ioBroker.

**Version information (please complete the following information):**
 - Extension version: [v0.9.2]
 - VS Code version: [1.55.2]
 - ioBroker admin version: [5.0.3]
 - ioBroker nodejs version: [14.15.3]
 - ioBroker javascript adapter version: [5.1.3]

**Comment by nokxs** [comment]
Ich verwende aktuell noch 4.2.1 mit welchem es funktioniert. Ich vermute mal, dass sich bei Admin > 5.0.0 die API geändert hat und es deswegen nicht mehr funktioniert.

**Comment by patrickbs96** [comment]
Kann gut sein, unter der Haube ist dort wohl viel passiert. Der läuft aktuell aber auch noch nicht stabil genug in der React Ansicht plus mir würde dieses Feature fehlen. Werde daher vorläufig noch zurück nach 4.2.1 wechseln. 
Aber dann weißt du schonmal Bescheid, dass sich eventuell etwas geändert hat

**Comment by nokxs** [comment]
Ich hab mir das inzwischen angeschaut und es scheint eine größere Anpassung nötig zu sein, da von ioBroker mit Admin 5 kein Socket.io mehr verwendet wird. Es wird wahrscheinlich noch etwas brauchen, bis ich das in der Extension nachgezogen habe.

**Comment by patrickbs96** [comment]
Danke für die schnelle Bearbeitung. Leider kriege ich jetzt weder mit Admin4 noch mit Admin5 ein Verbindung hin.
Die Config hatte ich um den Eintrag `"adminVersion": "admin4",` ergänzt.
Hast du da eine Idee? Kann ich dir irgendwelche Logs schicken?

**Comment by nokxs** [comment]
Die Doku war am Anfang falsch und aktuell bin ich wenig tolerant beim parsen. Versuch es mal mit einem großen "A": "Admin4" bzw. "Admin5".

**Comment by patrickbs96** [comment]
Das hat geklappt. Jetzt funktioniert die Verbindung in beiden Versionen 😄
