### ISSUE TITLE
Please close all Ordner at Start

### ISSUE THREAD

**Issue by markus2701** [nokxs/iobroker-javascript-vs-code-extension#4]
Please show all Ordner Closed at Start

**Comment by nokxs** [comment]
This is a good idea, as it is more flexible with a large amount of scripts. I will change the behaviour in one of the next releases.

**Comment by Feuer-sturm** [comment]
Is it possible to configure it in the config file? Default: close and everyone can change it how he likes it.

**Comment by nokxs** [comment]
@Feuer-sturm I will consider it. It shouldn't be too complicated to implet it configurable.

**Comment by nokxs** [comment]
As this feature was not difficult to implement, I've already done it. See [Readme](https://github.com/nokxs/iobroker-javascript-vs-code-extension#available-settings) on how to configure this.

**Comment by Feuer-sturm** [comment]
@nokxs Es gibt noch ein paar Probleme mit der Konfiguration. Hab hier mal ein neues Ticket https://github.com/nokxs/iobroker-javascript-vs-code-extension/issues/8 aufgemacht
