### ISSUE TITLE
ioBroker.javascript v0.11.0  Start Stop Icon wechselt nicht

### ISSUE THREAD

**Issue by Feuer-sturm** [nokxs/iobroker-javascript-vs-code-extension#48]
Admin 5.0.7 bzw. Admin 4.2.1
js-controller 3.2.16
ioBroker.javascript in VSCode 0.11.0

Wenn ein Skript über den "Play" Button gestartet wird, dann verändert sich nicht mehr das Symbol vor dem Skript. Gilt für Starten und Stoppen.
Das Skript wird erfolgreich gestartet / gestoppt. Es scheint eine reine Darstellungssache zu sein.

![grafik](https://user-images.githubusercontent.com/25422320/115917368-702c9c00-a476-11eb-9c78-34427f18e109.png)

**Comment by Feuer-sturm** [comment]
Problem tritt auch bei Admin 4.2.1 auf. Scheint somit nicht an der Admin Version zu liegen.

**Comment by nokxs** [comment]
Fixed in v0.11.2
