### ISSUE TITLE
Workspace

### ISSUE THREAD

**Issue by markus2701** [nokxs/iobroker-javascript-vs-code-extension#5]
um die Extension nutzen zu können, muss ich immer erst den lokalen Folder öffnen und kann dann die Extension starten, sonst funktioniert es nicht.
Kann man das ändern?

**Comment by nokxs** [comment]
Das wird erst einmal so bleiben, da man bei dem aktuellen Konzept die `iobroker-config.json` benötigt und diese muss in einem Verzeichnis liegen. Um das zu ändern, müsste ich das Grundkonzept anpassen (was ein größerer Aufwand wäre), was ich erst einmal nicht machen werde.
