### ISSUE TITLE
Can't connect to ioBroker

### ISSUE THREAD

**Issue by Seqway** [nokxs/iobroker-javascript-vs-code-extension#67]
**Describe the bug**
If I start the command to connect to ioBroker I get en error message

**To Reproduce**
see above

**Expected behavior**
According to the manual I should be asked to connect to my ioBroker server but instead I get an error message

**Screenshots**
![image](https://user-images.githubusercontent.com/40624961/138592267-6eb93a88-f0b0-4d92-9904-b9645570822e.png)

**Version information (please complete the following information):**
 - Extension version: v0.12.1
 - VS Code version: 1.61.2 (for MacOS Darwin x64 20.6.0)
 - ioBroker admin version: 5.1.25
 - ioBroker nodejs version: v12.22.7
 - ioBroker javascript adapter version: 5.2.8

**Comment by ciddi89** [comment]
You have to open a "Workspace" in the Explorer of Visual Code. It means to open a Folder where the config files and all other scripts of your ioBroker can be saved for it. In the first time if you start the Plugin, it will create a file called  iobroker-config.json. Here you can add the ip address an all other settings for connect to ioBroker.

**Comment by nokxs** [comment]
Close stale issue
