### ISSUE TITLE
Verbindung zum ioBroker wird nicht aufgebaut.

### ISSUE THREAD

**Issue by DerT94** [nokxs/iobroker-javascript-vs-code-extension#76]
Habe versucht die Erweiterung zum laufen zu bringen.
Allerdings kommt bei mir eine Fehlermeldung die sehr nichts sagend ist.
Im Log des ioBrokers kommt nichts an.

**config**
![image](https://user-images.githubusercontent.com/58786605/163163557-aa961bd6-1a8e-4a1d-8aa0-ab424a4ffdf6.png)

**.iobroker-config.json**
```
{
  "ioBrokerUrl": "http://iobroker.example.loc", 
  "socketIoPort": 8086,
  "scriptRoot": "/",
  "adminVersion": "Admin5"
}
```
**error message**
![image](https://user-images.githubusercontent.com/58786605/163162967-5e3c1672-dc07-4cab-a85e-edd1ac1646ef.png)

**Version information (please complete the following information):**
 - Extension version: 4.1.4
 - VS Code version:  Version: 1.66.2
 - ioBroker admin version: 5.3.4
 - ioBroker nodejs version: 12.22.1
 - ioBroker javascript adapter version: 5.2.21

**Comment by Feuer-sturm** [comment]
Ist dein iobroker per username und passwortgeschützt geschützt? Wenn ja, dann gibt es hier soweit ich es in Erinnerung habe noch keine Lösung/Umsetzung dafür.

Edit: siehe https://github.com/nokxs/iobroker-javascript-vs-code-extension#planned-features

**Comment by DerT94** [comment]
Ne eigentlich nicht.
Die web Oberfläche geht ohne Abfrage eines Benutzers auf.
Die Kommunikation läuft zwar über https mit meinem eigenen Zertifikat aber das sollte socket.io ja nicht stören oder ?

**Comment by nokxs** [comment]
Mit einem eigenen Zertifikat hab ich das noch nie probiert. Ich teste mal die nächsten Tage, ob dass das Problem ist.

Ist dein iobroker auch noch per http erreichbar? Hast du mal versucht in der config die URL mit "https://..." anstatt "http://..." anzugeben?

**Comment by DerT94** [comment]
Hab Testweise den Admin Adapter mal auf http umgestellt.
Dan erhalte ich eine andere Fehlermeldung
![image](https://user-images.githubusercontent.com/58786605/163546742-00a88bd4-8a09-4e31-ac1f-ca9b8f38d064.png)

Wenn ich als Adresse https versuche bekomme ich ebenfalls eine andere Fehlermeldung.
![image](https://user-images.githubusercontent.com/58786605/163546902-2114571f-bf1e-4839-abed-ffe01c227087.png)

Wenn ich zusätzlich den socket.io Adapter auf https umstelle bekomme ich die selbe Fehlermeldung wie bei http.
![image](https://user-images.githubusercontent.com/58786605/163547045-3077b5e1-33ef-42a9-aa8c-3cb306bfa4c2.png)

Die CA meines Zertifikats ist bei meinem System als Vertrauenswürdig hinterlegt und in VS Code ist auch die Einstellung gesetzt die System CAs zu verwenden.

**Comment by nokxs** [comment]
Läuft bei dir der ioBroker Admin Adapter ganz normal auf Port 8081? Wenn ja, bitte Port 8081 in der Config angeben (oder halt den Port des Admin Adapters).

Wenn ich jetzt so darüber nachdenke ist die Config hier etwas missverständlich, da die Kommunikation nicht über den SocketIo Adapter, sondern über das im Admin Adapter integrierte SocketIo läuft. Ich werde hier in Zukunft die Doku und Fehlermeldung etwas verbessern.

Das https-Thema schaue ich mir aber trotzdem auf jeden Fall demnächst mal an.

**Comment by DerT94** [comment]
und genau das war auch mein Fehler.
habe nun die ioBrokerUrl auf https stehen und den socketIoPort auf 8081.
Nun funktioniert es auch :)
Das heißt, https mit eigenem Zertifikat läuft auch.
