### ISSUE TITLE
Verhalten von expandDirectoriesOnStartup in config file

### ISSUE THREAD

**Issue by Feuer-sturm** [nokxs/iobroker-javascript-vs-code-extension#8]
Die Parameter funktionieren nicht, um das Ordner auf / zu beim starten zu konfigurieren
ioBroker Addon v.0.5.3

**i.O.**
```
{
  "ioBrokerUrl": "http://192.168.178.54",
  "socketIoPort": 8081,
  "workspaceSubPath": "/" 
}
```

**n.i.O**
```
{
  "ioBrokerUrl": "http://192.168.178.54",
  "socketIoPort": 8081,
  "workspaceSubPath": "/", // ★ Not supported yet
  "scriptExplorer": { // Configuration for script explorer
    "expandDirectoriesOnStartup": true // Should the directories in the script explorer be expanded on startup
  }
}
```
Es wird beim starten von VSCode nicht automatisch eine Verbindung mit ioBroker hergestellt. Wenn man über F1 eine Verbindung zu ioBroker triggert kommt folgende Fehlermeldung:

Fehlermeldung
Could not connect to ioBroker. Check your '.iobroker-config.json' for wrong configuration: SyntaxError: Unexpected token / in JSON at position 95

Es gibt anscheind Probleme mit den Kommentaren //
Wenn man die Kommentare rauslöscht wird automatisch wieder die Verbindung zu ioBroker hergestellt.
Laut Google :-) ist es nicht möglich Kommentare in ein json File zu schreiben. Dies sollte man dann am besten in der Readme entsprechend kenntlich machen, dass die Kommentare gelöscht werden müssen oder man baut die Readme anders auf mit einer config file die man 1:1 kopieren kann und daraunter eine Tabelle mit den entsprechenden Erklärungen

```
{
  "ioBrokerUrl": "http://192.168.178.54",
  "socketIoPort": 8081,
  "workspaceSubPath": "/", 
  "scriptExplorer": { 
    "expandDirectoriesOnStartup": false 
  }
}
```

Die Logik ist verkehrt herum:
    "expandDirectoriesOnStartup": false  führt dazu, dass die Ordner aufgeklappt sind beim starten von VSCode
    "expandDirectoriesOnStartup": true führt dazu, dass die Ordner zugeklappt sind beim starten von VSCode

**Comment by nokxs** [comment]
Erst einmal Danke für die ausführliche Meldung. 

Es war etwas leichtsinnig von mir die Kommentare ins Json zu schreiben. Ich hab das Ganze etwas anders dokumentiert. Kannst du mal schauen, ob das jetzt für dich verständlicher ist: https://github.com/nokxs/iobroker-javascript-vs-code-extension/blob/d099173f8377d9a6b55d2423f24c52ccbbd4fccb/README.md#available-settings?

Bei der Benennung `expandDirectoriesOnStartup` hab ich nicht ganau aufgepasst. Im code habe ich immer `collapsed`, also das Gegenteil verwendet. Daher ist die Logik verdreht. Ich habe jetzt `expandDirectoriesOnStartup` in `collapseDirectoriesOnStartup` umbenannt.

**Comment by Feuer-sturm** [comment]
Hallo @nokxs, für mich sieht die config + Erklärung gut aus :-)
collapseDirectoriesOnStartup passt für mich auch. Dann warte ich mal auf die neue Version um es zu testen.

**Comment by nokxs** [comment]
Die Version 0.6.0 enthält die Änderung.

**Comment by Feuer-sturm** [comment]
Top. Funktioniert auch :-)
