### ISSUE TITLE
Include Connection to Admin6

### ISSUE THREAD

**Issue by diwoma** [nokxs/iobroker-javascript-vs-code-extension#82]
**Is your feature request related to a problem? Please describe.**
Probiert mit Admin5:
Could not connect to ioBroker. Check your '.iobroker-config.json' for wrong configuration: Error: The connection to ioBroker was not possible. Reason: Error Code: UNKNOWN; Message: connect ECONNREFUSED

In config auf Admin6 gesetzt:
Could not connect to ioBroker. Check your '.iobroker-config.json' for wrong configuration: Error: Cannot determine which connection service to use. Configured admin version: admin6

**Describe the solution you'd like**
Ich weiss nicht, was sich in der Verbindung zu Admin6 geändert hat, aber ich musste wegen eines Adapters auf Admin6 umstellen.
Es sollte wieder gehen.

**Describe alternatives you've considered**

**Additional context**

**Comment by nokxs** [comment]
Bis jetzt habe ich mir noch nicht angeschaut, was sich bei Admin 6 geändert hat, dementsprechend wird dies aktuell noch nicht unterstützt. Ich werde dies die nächsten Tage machen und versuchen Admin 6 zu unterstützen.

**Comment by nokxs** [comment]
Ich habe es jetzt bei mir getestet und wenn man die Config auf Admin5 lässt (Admin6 kennt die Config noch nicht), dann sollte es funktionieren. Bei mir hat es mit Admin _6.2.4_ und Javascript _6.0.0_ und folgender Config funktioniert:

```json
{
  "ioBrokerUrl": "http://localhost",
  "socketIoPort": 8081,
  "scriptRoot": "/",
  "adminVersion": "admin5"
}
```

**Comment by diwoma** [comment]
Ja, danke. Mit der Einstellung hat es funktioniert. Mein Fehler war anscheinend, dass beim Versuch des Reconnect die Änderung der Config nicht übernommen worden war. Erst nach einem Restart des VS-Code hat funktioniert.

Danke für die Mühe.
-- Wolfgang

**Comment by Feuer-sturm** [comment]
Bei mir funktioniert iobroker-javascript-vs-code-extension mit Admin 6.2.4 auch ohne Probleme :-)
