### ISSUE TITLE
createTempDir on linux not work

### ISSUE THREAD

**Issue by dirkhe** [nokxs/iobroker-javascript-vs-code-extension#96]
**Describe the bug**
The function  
```
createTemporaryFile(fileName: string, content: string): Promise<Uri> {
        return new Promise((resolve, reject) => {
            const tempDir = os.tmpdir();
            fs.mkdtemp(`${tempDir}iobroker-`, ....
```
tried to create a directory like "/tmpiobroker-jjjjj". It should use "/tmp/iobroker-jjjjjj". So I guess the behavior on linux is different to windows.
Perhaps you should use Path.join(tempDir, "iobroker-")

**To Reproduce**
1. change a Script
2. Click on "show diff..."
3. You will get an error message like 
`Fehler beim Ausführen des Befehls iobroker-javascript.view.changed-scripts.showLocalToServerDiff: Ein Systemfehler ist aufgetreten (EACCES: permission denied, mkdtemp '/tmpiobroker-lnWVP4').. Dies wird vermutlich durch die Erweiterung verursacht, die iobroker-javascript.view.changed-scripts.showLocalToServerDiff beiträgt. `

**Expected behavior**
temp folder will be created

**Version information (please complete the following information):**
 - Extension version: 1.1.1
 - VS Code version: 1.70.2

**Comment by nokxs** [comment]
Thanks for the detailed analysis. I could reproduce it and I fixed it as suggested by you. Version 1.1.2 contains the fix.
