### ISSUE TITLE
After Upload the code is deleted

### ISSUE THREAD

**Issue by ChrisDuck87** [nokxs/iobroker-javascript-vs-code-extension#99]
In Version 1.1.3 following problem occur: 

If i edit a script in Visual basic and click afterwards the upload button the code is deleted in the Js-Instance. 
After download in visual basic, too. 

I do following steps: 

Original Script in IoBroker:
![image](https://user-images.githubusercontent.com/88966869/192155168-356e940e-58e1-4ed4-a56c-3c723ba3a6d9.png)

Code in Visual Basic: 
![image](https://user-images.githubusercontent.com/88966869/192155116-ea2d9347-9317-4125-b387-4e2ba99247a7.png)

Click on the Upload Button: 

![image](https://user-images.githubusercontent.com/88966869/192155147-ce5a74ef-22ae-4d16-b7ec-13486063bcbf.png)

Checking again the Skript - the Code is gone:

![image](https://user-images.githubusercontent.com/88966869/192155191-f3d232a9-c723-4def-87dd-e57ab8bb8445.png)

Best Christian

**Comment by ChrisDuck87** [comment]
EDIT: Found the issue, on my own: The file must be saved before uploading it to IoBroker. 

Maybe it is possible to sent a warning message if the data is NOT already saved in the directory, so that it not could be happend to upload/delete something.

**Comment by nokxs** [comment]
Good, that you found the problem yourself !

I have fixed the issue by disabling the upload button for scripts, which exists only on remote and are not downloaded yet. It looks like this:
![grafik](https://user-images.githubusercontent.com/5887690/192156621-38003ae3-3af4-4b19-a1d4-c69dc7d57a87.png)

This feature will be release with version 1.1.4

**Comment by ChrisDuck87** [comment]
Top! Thanks a lot! Really a great support!
